<a href="https://colab.research.google.com/github/Luiz-castilho/CalculoNumerico/blob/main/SistemasLineares.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

1. Sistemas lineares na forma matricial. Escreva cada sistema na forma Ax = b,
identificando a matriz dos coeficientes, o vetor de incógnitas e o vetor independente.
a)
$$
\begin{cases}
2x + y = 7, \\
x - 3y = -5.
\end{cases}
$$

b)
$$
\begin{cases}
x + 2y - z = 2, \\
3x - y + 2z = 9, \\
2x + y + z = 7.
\end{cases}
$$

In [1]:
import numpy as np
np.set_printoptions(precision=6, suppress=True)


A1 = np.array([[2., 1.],
              [1., 3.]])
b1 = np.array([7., -5.])
A2 = np.array([[1., 2.,  -1.],
              [3., -1., 2.],
              [2., 1., 1.]])
b2 = np.array([2., 9., 7.])

print("Matriz A1:\n", A1)
print("Vetor b1:", b1)
print("Matriz A1:\n", A2)
print("Vetor b1:", b2)

Matriz A1:
 [[2. 1.]
 [1. 3.]]
Vetor b1: [ 7. -5.]
Matriz A1:
 [[ 1.  2. -1.]
 [ 3. -1.  2.]
 [ 2.  1.  1.]]
Vetor b1: [2. 9. 7.]


2. Método da eliminação de Gauss. Resolva o sistema usando operações elementares
nas linhas. Mostre a matriz aumentada em cada etapa e faça a substituição regressiva.
$$
\begin{cases}
2x + y - z = 8, \\
-3x - y + 2z = -11, \\
-2x + y + 2z = -3.
\end{cases}
$$


Matrizes:
$$
A_2 = \begin{bmatrix}
2 & 1 & -1 \\
-3 & -1 & 2 \\
-2 & 1 & 2
\end{bmatrix}, \quad
b_2 = \begin{bmatrix}
8 \\
-11 \\
-3
\end{bmatrix}
$$


#### 2. Escalonamento (Eliminação Gaussiana)

##### Passo 1: Eliminar os elementos abaixo do pivô da 1ª coluna ($a_{11} = 2$)

* **Para a Linha 2 ($L_2$):** aplicamos $L_2 \leftarrow L_2 + \frac{3}{2}L_1$
  $$
  \begin{aligned}
  -3 + \frac{3}{2}(2) &= 0 \\
  -1 + \frac{3}{2}(1) &= \frac{1}{2} \\
  2 + \frac{3}{2}(-1) &= \frac{1}{2} \\
  -11 + \frac{3}{2}(8) &= -11 + 12 = 1
  \end{aligned}
  $$

* **Para a Linha 3 ($L_3$):** aplicamos $L_3 \leftarrow L_3 + L_1$
  $$
  \begin{aligned}
  -2 + 2 &= 0 \\
  1 + 1 &= 2 \\
  2 + (-1) &= 1 \\
  -3 + 8 &= 5
  \end{aligned}
  $$

A matriz fica:

$$
\left[\begin{array}{ccc|c}
2 & 1 & -1 & 8 \\
0 & \frac{1}{2} & \frac{1}{2} & 1 \\
0 & 2 & 1 & 5
\end{array}\right]
$$



##### Passo 2: Eliminar o elemento abaixo do pivô da 2ª coluna ($a_{22} = \frac{1}{2}$)

* **Para a Linha 3 ($L_3$):** aplicamos $L_3 \leftarrow L_3 - 4L_2$
  $$
  \begin{aligned}
  0 - 4(0) &= 0 \\
  2 - 4\left(\frac{1}{2}\right) &= 2 - 2 = 0 \\
  1 - 4\left(\frac{1}{2}\right) &= 1 - 2 = -1 \\
  5 - 4(1) &= 5 - 4 = 1
  \end{aligned}
  $$

A matriz na forma escalonada é:

$$
\left[\begin{array}{ccc|c}
2 & 1 & -1 & 8 \\
0 & \frac{1}{2} & \frac{1}{2} & 1 \\
0 & 0 & -1 & 1
\end{array}\right]
$$



#### 3. Substituição Regressiva

Reescrevemos o sistema triangular equivalente:

1. **Da terceira linha ($L_3$):**
   $$
   -x_3 = 1 \implies x_3 = -1
   $$

2. **Da segunda linha ($L_2$):**
   $$
   \frac{1}{2}x_2 + \frac{1}{2}x_3 = 1
   $$
   Substituindo $x_3 = -1$:
   $$
   \frac{1}{2}x_2 + \frac{1}{2}(-1) = 1 \implies \frac{1}{2}x_2 = 1 + \frac{1}{2} = \frac{3}{2} \implies x_2 = 3
   $$

3. **Da primeira linha ($L_1$):**
   $$
   2x_1 + x_2 - x_3 = 8
   $$
   Substituindo $x_2 = 3$ e $x_3 = -1$:
   $$
   2x_1 + 3 - (-1) = 8 \implies 2x_1 + 4 = 8 \implies 2x_1 = 4 \implies x_1 = 2
   $$



#### 4. Solução Final

O sistema possuí solução única:

$$
\mathbf{x} = \begin{bmatrix} x_1 \\ x_2 \\ x_3 \end{bmatrix} = \begin{bmatrix} 2 \\ 3 \\ -1 \end{bmatrix}
$$

In [2]:
A_2 = np.array([[2., 1.,  -1.],
              [-3., -1., 2.],
              [-2., 1., 2.]])
b_2 = np.array([8., -11., -3.])
M_2 = np.column_stack([A_2, b_2])
print("Matriz aumentada [A | b]:\n", M_2)

Matriz aumentada [A | b]:
 [[  2.   1.  -1.   8.]
 [ -3.  -1.   2. -11.]
 [ -2.   1.   2.  -3.]]


### 3. Número de soluções

Para determinar o número de soluções de cada sistema, aplicamos operações elementares por linhas sobre a matriz aumentada $[A \mid b]$ até obter a forma escalonada.


___
#### a)
$$
\begin{cases}
x + y = 3 \\
2x + 2y = 6
\end{cases}
$$

**Matriz aumentada inicial:**
$$
\left[\begin{array}{cc|c}
1 & 1 & 3 \\
2 & 2 & 6
\end{array}\right]
$$

**Redução por linhas:**
Aplicando $L_2 \leftarrow L_2 - 2L_1$:
$$
\left[\begin{array}{cc|c}
1 & 1 & 3 \\
2 - 2(1) & 2 - 2(1) & 6 - 2(3)
\end{array}\right]
=
\left[\begin{array}{cc|c}
1 & 1 & 3 \\
0 & 0 & 0
\end{array}\right]
$$

**Conclusão:**
A segunda linha é duas vezes a primeira e portanto elas são ld, o sistema possui infinitas soluções na forma y = -x + 3.


___

#### b)
$$
\begin{cases}
x + y = 3 \\
2x + 2y = 7
\end{cases}
$$

**Matriz aumentada inicial:**
$$
\left[\begin{array}{cc|c}
1 & 1 & 3 \\
2 & 2 & 7
\end{array}\right]
$$

**Redução por linhas:**
Aplicando $L_2 \leftarrow L_2 - 2L_1$:
$$
\left[\begin{array}{cc|c}
1 & 1 & 3 \\
2 - 2(1) & 2 - 2(1) & 7 - 2(3)
\end{array}\right]
=
\left[\begin{array}{cc|c}
1 & 1 & 3 \\
0 & 0 & 1
\end{array}\right]
$$

**Conclusão:**
Como a última linha termina com algo impossível ( 0*x + 0*y = 1) isso indica que o sistema não possui solução

___

#### c)
$$
\begin{cases}
x + y = 3 \\
2x - y = 0
\end{cases}
$$

**Matriz aumentada inicial:**
$$
\left[\begin{array}{cc|c}
1 & 1 & 3 \\
2 & -1 & 0
\end{array}\right]
$$

**Redução por linhas:**
1. Aplicando $L_2 \leftarrow L_2 - 2L_1$:
$$
\left[\begin{array}{cc|c}
1 & 1 & 3 \\
2 - 2(1) & -1 - 2(1) & 0 - 2(3)
\end{array}\right]
=
\left[\begin{array}{cc|c}
1 & 1 & 3 \\
0 & -3 & -6
\end{array}\right]
$$

2. Multiplicando $L_2 \leftarrow -\frac{1}{3}L_2$:
$$
\left[\begin{array}{cc|c}
1 & 1 & 3 \\
0 & 1 & 2
\end{array}\right]
$$

3. Eliminando o termo acima do pivô ($L_1 \leftarrow L_1 - L_2$):
$$
\left[\begin{array}{cc|c}
1 & 0 & 1 \\
0 & 1 & 2
\end{array}\right]
$$

**Conclusão:**
A matriz reduzida para esse caso fornece a solução direta do sistema tendo x = 1 e y = 2

In [8]:
import numpy as np

def eliminacao_gauss(A, b, eps=1e-8):
    A = np.array(A, dtype=float).copy()
    b = np.array(b, dtype=float).copy()
    n = len(b)
    flops = 0

    # 1. Eliminação Em Frente (Forward Elimination) SEM Pivotamento
    for i in range(n):
        # Verifica diretamente se o elemento diagonal é nulo/quase nulo
        if abs(A[i, i]) < eps:
            raise ValueError(f"Divisão por zero encontrada: pivô nulo na posição ({i}, {i}).")

        for j in range(i + 1, n):
            m = A[j, i] / A[i, i]
            flops += 1  # 1 divisão


            A[j] = A[j] - m * A[i]
            flops += 2 * n

            b[j] = b[j] - m * b[i]
            flops += 2

    # 2. Substituição Regressiva
    x = np.zeros(n)
    for i in range(n - 1, -1, -1):
        num_elem = n - 1 - i
        s = np.dot(A[i, i + 1:], x[i + 1:])
        if num_elem > 0:
            flops += 2 * num_elem
        x[i] = (b[i] - s) / A[i, i]
        flops += 2

    info_custo = {
        "flops": flops
    }

    return x, info_custo

### Resolução do Sistema Linear

O sistema de equações lineares associado à matriz é dado por:

$$
\begin{cases}
(1) \quad 4T_1 - T_2 = 15 \\
(2) \quad -T_1 + 4T_2 - T_3 = 10 \\
(3) \quad -T_2 + 3T_3 = 10
\end{cases}
$$

---

#### Passo 1: Isolar variáveis em função de $T_2$

A partir da equação $(1)$:
$$
4T_1 = 15 + T_2 \implies T_1 = \frac{15 + T_2}{4}
$$

A partir da equação $(3)$:
$$
3T_3 = 10 + T_2 \implies T_3 = \frac{10 + T_2}{3}
$$

---

#### Passo 2: Substituir $T_1$ e $T_3$ na equação $(2)$

Substituindo na equação $-T_1 + 4T_2 - T_3 = 10$:

$$
-\left(\frac{15 + T_2}{4}\right) + 4T_2 - \left(\frac{10 + T_2}{3}\right) = 10
$$

Multiplicando toda a equação por $12$ (o mínimo múltiplo comum entre $3$ e $4$):

$$
-3(15 + T_2) + 12(4T_2) - 4(10 + T_2) = 12 \cdot 10
$$

Expandindo os termos:

$$
-45 - 3T_2 + 48T_2 - 40 - 4T_2 = 120
$$

Agrupando os termos semelhantes:

$$
(-3 + 48 - 4)T_2 - (45 + 40) = 120
$$

$$
41T_2 - 85 = 120
$$

$$
41T_2 = 205 \implies T_2 = \frac{205}{41} = 5
$$

---

#### Passo 3: Determinar $T_1$ e $T_3$

Substituindo $T_2 = 5$ nas expressões isoladas:

* Para $T_1$:
$$
T_1 = \frac{15 + 5}{4} = \frac{20}{4} = 5
$$

* Para $T_3$:
$$
T_3 = \frac{10 + 5}{3} = \frac{15}{3} = 5
$$

---

#### Solução Final

$$
\begin{bmatrix}
T_1 \\
T_2 \\
T_3
\end{bmatrix}
=
\begin{bmatrix}
5 \\
5 \\
5
\end{bmatrix}
$$

In [13]:
A_4 = np.array([[4., -1.,  0.],
              [-1., 4., -1.],
              [0., -1., 3.]])
b_4 = np.array([15., 10., 10.])
sol, custo=eliminacao_gauss(A_4, b_4)
for idx, valor in enumerate(sol):
    print(f"x_{idx + 1} = {valor:.2f}")

x_1 = 5.00
x_2 = 5.00
x_3 = 5.00
